[package]
name = "riscv-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
memmap2 = "0.9.7"
paste = "1.0.15"
static_assertions = "1.1.0"
